
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action helpAction;
	private global::Gtk.Action ANGGANDANIMAAMKATLOLINTERPRETERAction;
	private global::Gtk.Action helpAction1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar3;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox5;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label label10;
	private global::Gtk.FileChooserButton fileOp;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView coded;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Fixed fixed14;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.Label label8;
	private global::Gtk.Fixed fixed5;
	private global::Gtk.Fixed fixed13;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TreeView lexemes;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Fixed fixed15;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.Label label9;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Fixed fixed16;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.TreeView symbol;
	private global::Gtk.Button exe;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Fixed fixed10;
	private global::Gtk.Fixed fixed9;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView console;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, "gtk-help");
		this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.helpAction, null);
		this.ANGGANDANIMAAMKATLOLINTERPRETERAction = new global::Gtk.Action ("ANGGANDANIMAAMKATLOLINTERPRETERAction", global::Mono.Unix.Catalog.GetString ("ANG GANDA NI MA'AM KAT LOLINTERPRETER"), null, null);
		this.ANGGANDANIMAAMKATLOLINTERPRETERAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("ANG GANDA NI MA'AM KAT LOLINTERPRETER");
		w1.Add (this.ANGGANDANIMAAMKATLOLINTERPRETERAction, null);
		this.helpAction1 = new global::Gtk.Action ("helpAction1", global::Mono.Unix.Catalog.GetString ("_Help"), null, "gtk-help");
		this.helpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.helpAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("ANG GANDA NI MA'AM TIN LOLINTERPRETER");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar3'><menu name='ANGGANDANIMAAMKATLOLINTERPRETERAction' action='ANGGANDANIMAAMKATLOLINTERPRETERAction'><menuitem name='helpAction1' action='helpAction1'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox1.Add (this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Code");
		this.hbox13.Add (this.label10);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label10]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.fileOp = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fileOp.Name = "fileOp";
		this.hbox13.Add (this.fileOp);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.fileOp]));
		w4.Position = 1;
		this.vbox5.Add (this.hbox13);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox13]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.coded = new global::Gtk.TextView ();
		this.coded.Buffer.Text = "HAI\nI HAS A VAR ITZ \"HI\"\nVISIBLE SMOOSH VAR AN VAR AN \"HELLO\"\nKTHXBYE";
		this.coded.CanFocus = true;
		this.coded.Name = "coded";
		this.GtkScrolledWindow.Add (this.coded);
		this.vbox5.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow]));
		w7.Position = 1;
		this.hbox1.Add (this.vbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
		w8.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fixed14 = new global::Gtk.Fixed ();
		this.fixed14.Name = "fixed14";
		this.fixed14.HasWindow = false;
		this.vbox3.Add (this.fixed14);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed14]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox6.Add (this.fixed3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed3]));
		w10.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Lexemes");
		this.hbox6.Add (this.label8);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label8]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox6.Add (this.fixed5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed5]));
		w12.Position = 2;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fixed13 = new global::Gtk.Fixed ();
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		this.vbox3.Add (this.fixed13);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed13]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.lexemes = new global::Gtk.TreeView ();
		this.lexemes.CanFocus = true;
		this.lexemes.Name = "lexemes";
		this.GtkScrolledWindow2.Add (this.lexemes);
		this.vbox3.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow2]));
		w16.Position = 3;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w17.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fixed15 = new global::Gtk.Fixed ();
		this.fixed15.Name = "fixed15";
		this.fixed15.HasWindow = false;
		this.vbox4.Add (this.fixed15);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed15]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox7.Add (this.fixed6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.fixed6]));
		w19.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Symbol Table");
		this.hbox7.Add (this.label9);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label9]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.hbox7.Add (this.fixed4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.fixed4]));
		w21.Position = 2;
		this.vbox4.Add (this.hbox7);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fixed16 = new global::Gtk.Fixed ();
		this.fixed16.Name = "fixed16";
		this.fixed16.HasWindow = false;
		this.vbox4.Add (this.fixed16);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed16]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.symbol = new global::Gtk.TreeView ();
		this.symbol.CanFocus = true;
		this.symbol.Name = "symbol";
		this.GtkScrolledWindow3.Add (this.symbol);
		this.vbox4.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow3]));
		w25.Position = 3;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w26.Position = 2;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w27.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.exe = new global::Gtk.Button ();
		this.exe.CanFocus = true;
		this.exe.Name = "exe";
		this.exe.UseUnderline = true;
		this.exe.Label = global::Mono.Unix.Catalog.GetString ("Execute");
		this.vbox1.Add (this.exe);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.exe]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed10 = new global::Gtk.Fixed ();
		this.fixed10.Name = "fixed10";
		this.fixed10.HasWindow = false;
		this.hbox5.Add (this.fixed10);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed10]));
		w29.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.hbox5.Add (this.fixed9);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed9]));
		w30.Position = 1;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.console = new global::Gtk.TextView ();
		this.console.CanFocus = true;
		this.console.Name = "console";
		this.console.Editable = false;
		this.console.Overwrite = true;
		this.console.AcceptsTab = false;
		this.GtkScrolledWindow1.Add (this.console);
		this.vbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
		w33.Position = 1;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w34.Position = 3;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 937;
		this.DefaultHeight = 584;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.fileOp.SelectionChanged += new global::System.EventHandler (this.OnFileOpSelectionChanged);
		this.exe.Clicked += new global::System.EventHandler (this.OnExeClicked);
	}
}
